DROP TABLE SVSERVER;
CREATE TABLE SVSERVER (
    ID NUMBER(38) PRIMARY KEY,
    CODE NUMBER(2),
    DIVISION NUMBER(2),
    DESCRIPTION NVARCHAR2(50),
    NAME VARCHAR2(255 CHAR),
    DIRECTORY VARCHAR2(4 CHAR),
    CODE2 VARCHAR2(2 CHAR),
    ORDINAL NUMBER(38)
);

DROP TABLE SVSERVERSETTINGS;
CREATE TABLE SVSERVERSETTINGS (
    SettingName VARCHAR2(20 CHAR) PRIMARY KEY,
    SettingValue VARCHAR2(255 CHAR),
    IsExpired NUMBER(1,0) NULL,
    Description VARCHAR2(500 CHAR) NULL
);

DROP TABLE PRCL;
CREATE TABLE PRCL (
    RECTYPE NUMBER(3),
    GRUPNUM VARCHAR2(8 CHAR),
    EFCTYYYYMM VARCHAR2(6 CHAR),
    MEMBSEL VARCHAR2(10 CHAR),
    CLNTNUM VARCHAR2(8 CHAR),
    KJSLANAME NVARCHAR2(30),
    KJGLANAME NVARCHAR2(20),
    KSULANAME NVARCHAR2(30),
    KGILANAME NVARCHAR2(20),
    KLADOB VARCHAR2(8 CHAR),
    KLASEX VARCHAR2(1 CHAR) DEFAULT 'M',
    KLAADDRCD VARCHAR2(11 CHAR),
    KLAPOSTCDE VARCHAR2(10 CHAR),
    OCCUP VARCHAR2(4 CHAR),
    KBN1RLN NUMBER(5),
    KBN1PS NUMBER(5),
    ZLNFLAG VARCHAR2(1 CHAR),
    ZDPFLAG VARCHAR2(1 CHAR),
    ZCRTBL VARCHAR2(2 CHAR),
    ZRCESTRM NUMBER(5),
    ZSUMINS NUMBER(9),
    KCOVPREM NUMBER(9),
    KTOTPRM NUMBER(9),
    ZSEQ10 VARCHAR2(10 CHAR),
    ZDATSEND VARCHAR2(8 CHAR),
    KCMPFLAG VARCHAR2(1 CHAR),
    
    constraint PK_PRCL primary key (GRUPNUM, EFCTYYYYMM, ZSEQ10)
);

DROP TABLE PRGR;
CREATE TABLE PRGR (
    RECTYPE NUMBER(3),
    KGRPTYPE NUMBER(3),
    GRUPNUM VARCHAR2(8 CHAR),
    EFCTYYYYMM VARCHAR2(6 CHAR),
    KJSOWNAME NVARCHAR2(30),
    KJGOWNAME NVARCHAR2(20),
    KSUOWNAME NVARCHAR2(30),
    KGIOWNAME NVARCHAR2(20),
    KOWDOB VARCHAR2(8 CHAR),
    KOWSEX VARCHAR2(1 CHAR) DEFAULT 'M',
    KOWADDRCD VARCHAR2(11 CHAR),
    KOWPOSTCDE VARCHAR2(10 CHAR),
    BILLFREQ VARCHAR2(2 CHAR),
    MOP VARCHAR2(1 CHAR),
    KTOTCNT NUMBER(9),
    OCCDATE VARCHAR2(8 CHAR),
    CCDATE VARCHAR2(8 CHAR),
    BRANCH VARCHAR2(2 CHAR),
    ZAGCYNUM VARCHAR2(5 CHAR),
    ZAGNTNUM VARCHAR2(5 CHAR),
    KJOINRAT NUMBER(5),
    KSNDCNT INT,
    ZDATSEND VARCHAR2(8 CHAR),
    ZVRSNSVF NUMBER(5),
    ZVRSNSLT VARCHAR2(8 CHAR),
    ENTDATE VARCHAR2(8 CHAR),
    ENTTIME VARCHAR2(6 CHAR),
    ZBKCODE VARCHAR2(4 CHAR),
    ZBKCLCDE VARCHAR2(12 CHAR),
    
    constraint PK_PRGR primary key (GRUPNUM, EFCTYYYYMM)
);

--Insert failed for rows  1  through  40 
--ORA-00001: unique constraint (INTERSHIP.SYS_C0027065) violated
--Row 1
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (1,0,0,N'??','C:\IS_TEST\Pctool','00','00',38);
--Row 2
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (2,0,60,N'??????????','C:\IS_TEST\Pctool','06','00',39);
--Row 3
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (3,2,0,N'???????',NULL,NULL,'02',37);
--Row 4
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (3,2,0,N'?????',NULL,NULL,'02',37);
--Row 5
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (5,10,0,N'?????','C:\IS_TEST\Pctool','2A','2A',1);
--Row 6
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (6,20,0,N'?????','C:\IS_TEST\Pctool','2D','2D',2);
--Row 7
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (7,21,0,N'?????','C:\IS_TEST\Pctool','2C','2C',3);
--Row 8
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (8,22,0,N'?????','C:\IS_TEST\Pctool','2E','2E',4);
--Row 9
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (9,30,0,N'??????','C:\IS_TEST\Pctool','1B','1B',17);
--Row 10
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (10,31,0,N'??????','C:\IS_TEST\Pctool','1C','1C',18);
--Row 11
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (11,32,0,N'???????','C:\IS_TEST\Pctool','3D','3D',7);
--Row 12
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (12,33,0,N'?????','C:\IS_TEST\Pctool','3F','3F',8);
--Row 13
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (13,34,0,N'??????','C:\IS_TEST\Pctool','1A','1A',16);
--Row 14
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (14,35,0,N'?????','C:\IS_TEST\Pctool','4A','4A',9);
--Row 15
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (15,36,0,N'??????','C:\IS_TEST\Pctool','1D','1D',19);
--Row 16
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (16,37,0,N'?????','C:\IS_TEST\Pctool','3A','3A',10);
--Row 17
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (17,38,0,N'?????','C:\IS_TEST\Pctool','3E','3E',5);
--Row 18
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (18,39,0,N'??????','C:\IS_TEST\Pctool','3B','3B',6);
--Row 19
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (19,40,0,N'?????','C:\IS_TEST\Pctool','3G','3G',11);
--Row 20
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (20,41,0,N'?????','C:\IS_TEST\Pctool','4B','4B',12);
--Row 21
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (21,50,0,N'????????','C:\IS_TEST\Pctool','4C','4C',13);
--Row 22
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (22,51,0,N'?????','C:\IS_TEST\Pctool','5H','5H',20);
--Row 23
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (23,52,0,N'?????','C:\IS_TEST\Pctool','4F','4F',15);
--Row 24
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (24,53,0,N'????????','C:\IS_TEST\Pctool','4D','4D',14);
--Row 25
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (25,60,0,N'??????','C:\IS_TEST\Pctool','5B','5B',22);
--Row 26
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (26,61,0,N'?????','C:\IS_TEST\Pctool','5F','5F',24);
--Row 27
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (27,63,0,N'?????','C:\IS_TEST\Pctool','5E','5E',25);
--Row 28
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (28,64,0,N'??????','C:\IS_TEST\Pctool','5A','5A',21);
--Row 29
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (29,65,0,N'??????','C:\IS_TEST\Pctool','5C','5C',23);
--Row 30
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (30,70,0,N'?????','C:\IS_TEST\Pctool','6B','6B',26);
--Row 31
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (31,71,0,N'?????','C:\IS_TEST\Pctool','6A','6A',27);
--Row 32
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (32,72,0,N'?????','C:\IS_TEST\Pctool','6C','6C',28);
--Row 33
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (33,73,0,N'?????','C:\IS_TEST\Pctool','6D','6D',29);
--Row 34
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (34,80,0,N'???????','C:\IS_TEST\Pctool','7A','7A',30);
--Row 35
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (35,82,0,N'??????','C:\IS_TEST\Pctool','7E','7E',34);
--Row 36
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (36,83,0,N'?????','C:\IS_TEST\Pctool','7D','7D',33);
--Row 37
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (37,84,0,N'???????','C:\IS_TEST\Pctool','7B','7B',31);
--Row 38
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (38,85,0,N'?????','C:\IS_TEST\Pctool','7F','7F',35);
--Row 39
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (39,86,0,N'??????','C:\IS_TEST\Pctool','7C','7C',32);
--Row 40
INSERT INTO SVSERVER (ID, CODE, DIVISION, DESCRIPTION, NAME, DIRECTORY, CODE2, ORDINAL) VALUES (40,99,99,N'WebMEGA','\\Wpjpd06C:\IS_TEST\Pctool','WEB',NULL,99);

/*===========================================*/
INSERT INTO "INTERSHIP"."PRGR" (RECTYPE, KGRPTYPE, GRUPNUM, EFCTYYYYMM, KJSOWNAME, KOWDOB, KOWSEX, KOWADDRCD, KOWPOSTCDE, BILLFREQ, MOP, KTOTCNT, OCCDATE, CCDATE, BRANCH, ZAGCYNUM, ZAGNTNUM, KJOINRAT, KSNDCNT, ZDATSEND) VALUES ('1', '1', '235128', '201808', N'??????', '0', 'C', '14106038001', '2400002', '1', 'G', '3', '20180829', '20180829', '0', '2JC6H', '79569', '100', '3', '20180920');

INSERT INTO "INTERSHIP"."PRCL" (RECTYPE, GRUPNUM, EFCTYYYYMM, KJSLANAME, KJGLANAME, KSULANAME, KGILANAME, KLADOB, KLASEX, KLAADDRCD, KLAPOSTCDE, OCCUP, KBN1RLN, KBN1PS, ZLNFLAG, ZDPFLAG, ZCRTBL, ZRCESTRM, ZSUMINS, KCOVPREM, KTOTPRM, ZSEQ10, ZDATSEND) VALUES ('2', '235128', '201808', N'????1', N'?1', N'??????', N'????', '19751010', 'M', '12227006004', '2790002', 'AA00', '50', '100', 'N', 'N', 'TP', '20', '20000000', '125440', '125440', '10018', '20180920');
INSERT INTO "INTERSHIP"."PRCL" (RECTYPE, GRUPNUM, EFCTYYYYMM, KJSLANAME, KJGLANAME, KSULANAME, KGILANAME, KLADOB, KLASEX, KLAADDRCD, KLAPOSTCDE, OCCUP, KBN1RLN, KBN1PS, ZLNFLAG, ZDPFLAG, ZCRTBL, ZRCESTRM, ZSUMINS, KCOVPREM, KTOTPRM, ZSEQ10, ZDATSEND) VALUES ('2', '235128', '201808', N'????2', N'?2', N'??????', N'???', '19681010', 'F', '12227004001', '2790003', 'AA01', '50', '100', 'N', 'N', 'TP', '20', '20000000', '112540', '112540', '190018', '20180920');
INSERT INTO "INTERSHIP"."PRCL" (RECTYPE, GRUPNUM, EFCTYYYYMM, KJSLANAME, KJGLANAME, KSULANAME, KGILANAME, KLADOB, KLASEX, KLAADDRCD, KLAPOSTCDE, OCCUP, KBN1RLN, KBN1PS, ZLNFLAG, ZDPFLAG, ZCRTBL, ZRCESTRM, ZSUMINS, KCOVPREM, KTOTPRM, ZSEQ10, ZDATSEND) VALUES ('2', '235128', '201808', N'????3', N'?3', N'??????', N'????', '19681010', 'F', '12227004001', '2790003', 'BA00', '50', '100', 'N', 'N', 'TP', '20', '20000000', '112540', '112540', '290018', '20180920');
