export const selectCountry: any = {
  flag: true,
  code: 20000,
  message: 'Request is successful.',
  data: {
    userId: 17,
    greatChina: [
      {
        countryId: 156,
        countryName: 'China',
        isInbound: true,
        isOutbound: true,
        region: 1,
      },
      {
        countryId: 158,
        countryName: 'Taiwan China',
        isInbound: true,
        isOutbound: true,
        region: 1,
      },
      {
        countryId: 344,
        countryName: 'Hong Kong China',
        isInbound: true,
        isOutbound: true,
        region: 1,
      },
    ],
    europe: [
      {
        countryId: 40,
        countryName: 'Austria',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 203,
        countryName: 'Czech Republic',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 208,
        countryName: 'Denmark',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 246,
        countryName: 'Finland',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 250,
        countryName: 'France',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 276,
        countryName: 'Germany',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 348,
        countryName: 'Hungary',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 356,
        countryName: 'India',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 376,
        countryName: 'Israel',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 380,
        countryName: 'Italy',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 528,
        countryName: 'Netherlands',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 578,
        countryName: 'Norway',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 616,
        countryName: 'Poland',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 620,
        countryName: 'Portugal',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 642,
        countryName: 'Romania',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 643,
        countryName: 'Russia',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 703,
        countryName: 'Slovakia',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 705,
        countryName: 'Slovenia',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 710,
        countryName: 'South Africa',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 724,
        countryName: 'Spain',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 752,
        countryName: 'Sweden',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 756,
        countryName: 'Switzerland',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 784,
        countryName: 'United Arab Emirates',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 792,
        countryName: 'Turkey',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 804,
        countryName: 'Ukraine',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
      {
        countryId: 826,
        countryName: 'Great Britain',
        isInbound: false,
        isOutbound: false,
        region: 2,
      },
    ],
    asiaPacific: [
      {
        countryId: 36,
        countryName: 'Australia',
        isInbound: false,
        isOutbound: false,
        region: 3,
      },
      {
        countryId: 360,
        countryName: 'Indonesia',
        isInbound: false,
        isOutbound: true,
        region: 3,
      },
      {
        countryId: 392,
        countryName: 'Japan',
        isInbound: true,
        isOutbound: true,
        region: 3,
      },
      {
        countryId: 410,
        countryName: 'South Korea',
        isInbound: true,
        isOutbound: true,
        region: 3,
      },
      {
        countryId: 458,
        countryName: 'Malaysia',
        isInbound: true,
        isOutbound: true,
        region: 3,
      },
      {
        countryId: 608,
        countryName: 'Philippines',
        isInbound: true,
        isOutbound: true,
        region: 3,
      },
      {
        countryId: 702,
        countryName: 'Singapore',
        isInbound: true,
        isOutbound: true,
        region: 3,
      },
      {
        countryId: 704,
        countryName: 'Vietnam',
        isInbound: true,
        isOutbound: true,
        region: 3,
      },
      {
        countryId: 764,
        countryName: 'Thailand',
        isInbound: true,
        isOutbound: true,
        region: 3,
      },
    ],
    america: [
      {
        countryId: 32,
        countryName: 'Argentina',
        isInbound: false,
        isOutbound: false,
        region: 4,
      },
      {
        countryId: 76,
        countryName: 'Brazil',
        isInbound: false,
        isOutbound: false,
        region: 4,
      },
      {
        countryId: 124,
        countryName: 'Canada',
        isInbound: false,
        isOutbound: false,
        region: 4,
      },
      {
        countryId: 152,
        countryName: 'Chile',
        isInbound: false,
        isOutbound: false,
        region: 4,
      },
      {
        countryId: 170,
        countryName: 'Colombia',
        isInbound: false,
        isOutbound: false,
        region: 4,
      },
      {
        countryId: 484,
        countryName: 'Mexico',
        isInbound: false,
        isOutbound: false,
        region: 4,
      },
      {
        countryId: 604,
        countryName: 'Peru',
        isInbound: false,
        isOutbound: false,
        region: 4,
      },
      {
        countryId: 840,
        countryName: 'USA',
        isInbound: false,
        isOutbound: false,
        region: 4,
      },
    ],
  },
};
