export const containerList: any = {
  flag: true,
  code: 20000,
  message: 'request success',
  data: {
    total: 2970,
    rows: [
      {
        id: '1',
        favorite: false,
        riskLevel: '0',
        remarked: true,
        containerNumber: 'ACLU9673613',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEHAM',
        to: 'USNYC',
        reqDeliveryDate: '2019-04-28',
        estDeliveryDate: '2019-04-24',
        actDeliveryDate: '2019-04-24',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00372558',
        eta: '',
      },
      {
        id: '2',
        favorite: false,
        riskLevel: '0',
        remarked: true,
        containerNumber: 'ACLU9679057',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEHAM',
        to: 'USNYC',
        reqDeliveryDate: '2019-06-16',
        estDeliveryDate: '2019-06-12',
        actDeliveryDate: '2015-08-14',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00387676',
        eta: '',
      },
      {
        id: '3',
        favorite: false,
        riskLevel: '0',
        remarked: true,
        containerNumber: 'ACLU9692845',
        forwarder: 'ff-kuehne+nagel',
        from: 'GBLIV',
        to: 'USNYC',
        reqDeliveryDate: '2019-05-08',
        estDeliveryDate: '2019-05-27',
        actDeliveryDate: '2019-05-27',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00384370',
        eta: '',
      },
      {
        id: '4',
        favorite: false,
        riskLevel: '0',
        remarked: false,
        containerNumber: 'ACLU9701799',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEHAM',
        to: 'USNYC',
        reqDeliveryDate: '2019-04-25',
        estDeliveryDate: '2019-04-16',
        actDeliveryDate: '2019-04-16',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00364232',
        eta: '',
      },
      {
        id: '',
        favorite: false,
        riskLevel: '0',
        remarked: false,
        containerNumber: 'ACLU9721584',
        forwarder: 'ff-kuehne+nagel',
        from: 'GBLIV',
        to: 'USNYC',
        reqDeliveryDate: '2019-05-22',
        estDeliveryDate: '2019-06-07',
        actDeliveryDate: '2019-06-20',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00392318',
        eta: '',
      },
      {
        id: '',
        favorite: false,
        riskLevel: '0',
        remarked: true,
        containerNumber: 'ACLU9728341',
        forwarder: 'ff-kuehne+nagel',
        from: 'GBLIV',
        to: 'USNYC',
        reqDeliveryDate: '2019-05-01',
        estDeliveryDate: '2019-05-19',
        actDeliveryDate: '2019-05-20',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00384359',
        eta: '',
      },
      {
        id: '5',
        favorite: false,
        riskLevel: '0',
        remarked: true,
        containerNumber: 'ACLU9730415',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEHAM',
        to: 'USNYC',
        reqDeliveryDate: '2019-06-22',
        estDeliveryDate: '2019-06-18',
        actDeliveryDate: '',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00387762',
        eta: '',
      },
      {
        id: '6',
        favorite: false,
        riskLevel: '0',
        remarked: true,
        containerNumber: 'ACLU9734283',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEHAM',
        to: 'USNYC',
        reqDeliveryDate: '2019-05-14',
        estDeliveryDate: '2019-05-08',
        actDeliveryDate: '2019-05-08',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00375538',
        eta: '',
      },
      {
        id: '7',
        favorite: false,
        riskLevel: '0',
        remarked: false,
        containerNumber: 'ACLU9735150',
        forwarder: 'ff-kuehne+nagel',
        from: 'GBLIV',
        to: 'USNYC',
        reqDeliveryDate: '2019-04-24',
        estDeliveryDate: '2019-05-12',
        actDeliveryDate: '2019-05-12',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00377681',
        eta: '',
      },
      {
        id: '8',
        favorite: false,
        riskLevel: '0',
        remarked: false,
        containerNumber: 'ACLU9754504',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEHAM',
        to: 'USNYC',
        reqDeliveryDate: '2019-05-29',
        estDeliveryDate: '2019-06-05',
        actDeliveryDate: '2015-08-13',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00376299',
        eta: '',
      },
      {
        id: '9',
        favorite: false,
        riskLevel: '0',
        remarked: false,
        containerNumber: 'ACLU9759168',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEHAM',
        to: 'USNYC',
        reqDeliveryDate: '2019-05-28',
        estDeliveryDate: '2019-05-29',
        actDeliveryDate: '2015-08-13',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00376298',
        eta: '',
      },
      {
        id: '',
        favorite: false,
        riskLevel: '0',
        remarked: false,
        containerNumber: 'ACLU9761329',
        forwarder: 'ff-kuehne+nagel',
        from: 'GBLIV',
        to: 'USNYC',
        reqDeliveryDate: '2019-05-01',
        estDeliveryDate: '2019-05-19',
        actDeliveryDate: '2016-11-30',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00384358',
        eta: '',
      },
      {
        id: '',
        favorite: false,
        riskLevel: '0',
        remarked: true,
        containerNumber: 'ACLU9774970',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEHAM',
        to: 'USNYC',
        reqDeliveryDate: '2019-05-20',
        estDeliveryDate: '2019-05-23',
        actDeliveryDate: '2019-05-23',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00376297',
        eta: '',
      },
      {
        id: '10',
        favorite: false,
        riskLevel: '0',
        remarked: true,
        containerNumber: 'ACLU9778717',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEHAM',
        to: 'USNYC',
        reqDeliveryDate: '2019-06-29',
        estDeliveryDate: '2019-06-19',
        actDeliveryDate: '2015-08-19',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'ACLUSA00397393',
        eta: '',
      },
      {
        id: '',
        favorite: false,
        riskLevel: '0',
        remarked: false,
        containerNumber: 'AKLU6500856',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEHAM',
        to: 'JPTYO',
        reqDeliveryDate: '2019-06-05',
        estDeliveryDate: '2019-05-25',
        actDeliveryDate: '2019-06-05',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'HAMV32079700',
        eta: '',
      },
      {
        id: '11',
        favorite: false,
        riskLevel: '0',
        remarked: false,
        containerNumber: 'AMFU3177673',
        forwarder: 'ff-kuehne+nagel',
        from: 'VNVUT',
        to: 'USLGB',
        reqDeliveryDate: '2019-04-10',
        estDeliveryDate: '2019-05-08',
        actDeliveryDate: '2019-05-08',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'HLCUSGN190339101',
        eta: '',
      },
      {
        id: '12',
        favorite: false,
        riskLevel: '0',
        remarked: false,
        containerNumber: 'AMFU8776289',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEBRV',
        to: 'USCHS',
        reqDeliveryDate: '2019-07-02',
        estDeliveryDate: '2019-06-26',
        actDeliveryDate: '2019-06-28',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'MEDUBN865234',
        eta: '',
      },
      {
        id: '13',
        favorite: false,
        riskLevel: '0',
        remarked: false,
        containerNumber: 'AMFU8899663',
        forwarder: 'ff-kuehne+nagel',
        from: 'DEBRV',
        to: 'CAMTR',
        reqDeliveryDate: '2019-05-23',
        estDeliveryDate: '2019-06-15',
        actDeliveryDate: '2019-06-19',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: 'MEDUBN849030',
        eta: '',
      },
      {
        id: '14',
        favorite: false,
        riskLevel: '0',
        remarked: true,
        containerNumber: 'APMU2844591',
        forwarder: 'ff-panalpina',
        from: 'DEBRV',
        to: 'CNSHA',
        reqDeliveryDate: '2019-04-02',
        estDeliveryDate: '2019-05-08',
        actDeliveryDate: '2019-07-01',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: '581015174',
        eta: '',
      },
      {
        id: '15s',
        favorite: false,
        riskLevel: '0',
        remarked: true,
        containerNumber: 'APMU2844591',
        forwarder: 'ff-panalpina',
        from: 'DEHAM',
        to: 'CNSHA',
        reqDeliveryDate: '2019-04-02',
        estDeliveryDate: '2019-05-08',
        actDeliveryDate: '2019-07-01',
        milestone: 'No milestone, tracked by forwarder',
        etaChange: 0,
        mbl: '581015174',
        eta: '',
      },
    ],
  },
};
