version: "3.8"
services:
  backend:
    container_name: laravel
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html/backend
      - enlive-vendor:/var/www/html/backend/vendor
      - ./backend/docker-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
    networks:
      - app
  frontend:
    container_name: next_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/var/www/html/frontend
    depends_on:
      - backend
    networks:
      - app
  db:
    container_name: db
    image: mysql:5.7.32
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testxdebug
      MYSQL_USER: testxdebuguser
      MYSQL_PASSWORD: P@ssword123
      MYSQL_ROOT_PASSWORD: P@ssword123
    networks:
      - app
  nginx:
    container_name: nginx
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html/backend
      - enlive-vendor:/var/www/html/backend/vendor
      - ./frontend:/var/www/html/frontend
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  enlive-vendor:
