version: "3.8"
services:
  frontend:
    container_name: next_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ${ENVIRONMENT}
    volumes:
      - ./frontend:/var/www/html/frontend
    networks:
      - app
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - NGINX_ENV=${ENVIRONMENT}
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx/nginx.${ENVIRONMENT}.conf:/etc/nginx/conf.d/nginx.${ENVIRONMENT}.conf
    depends_on:
      - frontend
    networks:
      - app
networks:
  app:
    driver: bridge
